#include "usermod_v2_device_manager.h"

// AI: below section was generated by an AI
// Define static name string
const char UsermodDeviceManager::_name[] PROGMEM = "DeviceManager";

// Instantiation and registration of Device Manager Usermod
#ifdef USERMOD_DEVICE_MANAGER
static UsermodDeviceManager deviceManagerUsermod;
REGISTER_USERMOD(deviceManagerUsermod);
#endif
// AI: end
