#pragma once

#include "wled.h"

// AI: below section was generated by an AI
/*
 * Automation Engine Usermod for WLED
 * Evaluates Triggers (Time/Schedule, Sunrise/Sunset, WLED State/Preset changes, MQTT messages)
 * and executes Actions (Apply Preset, Toggle Power/Relay, JSON/HTTP API Commands).
 */

#define AUTOMATION_ENGINE_MAX_RULES 16
#define AUTOMATION_ENGINE_FILE_PATH "/automations.json"

enum TriggerType {
  TRIG_TIME = 0,
  TRIG_SUNRISE_SUNSET = 1,
  TRIG_STATE_CHANGE = 2,
  TRIG_MQTT = 3
};

enum ActionType {
  ACT_PRESET = 0,
  ACT_POWER_TOGGLE = 1,
  ACT_API_COMMAND = 2
};

struct AutomationRule {
  uint8_t id = 0;
  bool enabled = true;
  char name[32] = "";
  
  TriggerType triggerType = TRIG_TIME;
  // Trigger parameters
  uint8_t timeHour = 0;
  uint8_t timeMinute = 0;
  uint8_t daysOfWeek = 0x7F; // Bitmask (bit 0 = Sun, bit 6 = Sat)
  uint8_t solarType = 0;     // 0 = Sunrise, 1 = Sunset
  int16_t solarOffset = 0;   // Offset in minutes
  uint8_t stateType = 0;     // 0 = Power ON/OFF, 1 = Preset change
  uint8_t stateVal = 0;      // Target preset ID or power state
  char mqttTopic[64] = "";
  char mqttPayload[32] = "";
  
  ActionType actionType = ACT_PRESET;
  // Action parameters
  uint8_t presetId = 1;
  uint8_t powerState = 2;    // 0 = Off, 1 = On, 2 = Toggle
  char apiCommand[128] = "";

  // Runtime evaluation state
  uint32_t lastTriggeredTime = 0;
};

class UsermodAutomationEngine : public Usermod {
private:
  bool enabled = true;
  bool initDone = false;
  bool isExecuting = false; // Recursion guard during state changes
  unsigned long lastLoopTick = 0;
  uint8_t lastEvaluatedMinute = 255;

  AutomationRule rules[AUTOMATION_ENGINE_MAX_RULES];
  uint8_t ruleCount = 0;

  static const char _name[];

  // Helper for safe null-terminated string copying
  static void safeCopy(char* dest, const char* src, size_t destSize) {
    if (!dest || destSize == 0) return;
    if (!src) {
      dest[0] = '\0';
      return;
    }
    strncpy(dest, src, destSize - 1);
    dest[destSize - 1] = '\0';
  }

  // Helper: execute assigned action for a matched rule
  void executeAction(const AutomationRule& rule) {
    if (!rule.enabled || isExecuting) return;

    isExecuting = true;
    DEBUG_PRINTF("Automation Engine: Rule #%d ('%s') triggered!\n", rule.id, rule.name);

    switch (rule.actionType) {
      case ACT_PRESET:
        if (rule.presetId > 0) {
          applyPreset(rule.presetId);
        }
        break;

      case ACT_POWER_TOGGLE:
        if (rule.powerState == 0 && bri > 0) {
          toggleOnOff();
          stateUpdated(CALL_MODE_DIRECT_CHANGE);
        } else if (rule.powerState == 1 && bri == 0) {
          toggleOnOff();
          stateUpdated(CALL_MODE_DIRECT_CHANGE);
        } else if (rule.powerState == 2) {
          toggleOnOff();
          stateUpdated(CALL_MODE_DIRECT_CHANGE);
        }
        break;

      case ACT_API_COMMAND:
        if (strlen(rule.apiCommand) > 0) {
          DynamicJsonDocument doc(512);
          DeserializationError err = deserializeJson(doc, rule.apiCommand);
          if (!err) {
            JsonObject obj = doc.as<JsonObject>();
            deserializeState(obj, CALL_MODE_DIRECT_CHANGE);
          } else {
            DEBUG_PRINTLN("Automation Engine: Failed to parse API command JSON");
          }
        }
        break;
    }

    isExecuting = false;
  }

public:
  void setup() override {
    loadRules();
    initDone = true;
  }

  void loop() override {
    if (!enabled || !initDone) return;

    // Evaluate time-based triggers once every second (check minute transition)
    if (millis() - lastLoopTick >= 1000) {
      lastLoopTick = millis();

      time_t local = localTime;
      if (local == 0) return; // Time not synchronized yet

      uint8_t currentMinute = minute(local);
      uint8_t currentHour = hour(local);
      uint8_t currentWday = weekday(local) - 1; // 0 = Sunday

      if (currentMinute != lastEvaluatedMinute) {
        lastEvaluatedMinute = currentMinute;

        for (uint8_t i = 0; i < ruleCount; i++) {
          if (!rules[i].enabled) continue;

          if (rules[i].triggerType == TRIG_TIME) {
            bool dayMatch = (rules[i].daysOfWeek & (1 << currentWday)) != 0;
            if (dayMatch && rules[i].timeHour == currentHour && rules[i].timeMinute == currentMinute) {
              executeAction(rules[i]);
            }
          } else if (rules[i].triggerType == TRIG_SUNRISE_SUNSET) {
            // Check solar calculation epoch match
            time_t solarTime = (rules[i].solarType == 0) ? sunrise : sunset;
            if (solarTime > 0) {
              time_t targetSolarEpoch = solarTime + (rules[i].solarOffset * 60);
              int32_t diffSec = (int32_t)(local - targetSolarEpoch);
              if (abs(diffSec) < 30 && (millis() - rules[i].lastTriggeredTime > 120000)) {
                rules[i].lastTriggeredTime = millis();
                executeAction(rules[i]);
              }
            }
          }
        }
      }
    }
  }

  void onStateChange(uint8_t mode) override {
    if (!enabled || !initDone || isExecuting) return;

    for (uint8_t i = 0; i < ruleCount; i++) {
      if (!rules[i].enabled) continue;

      if (rules[i].triggerType == TRIG_STATE_CHANGE) {
        if (rules[i].stateType == 0) { // Power state trigger
          bool currentPowerState = (bri > 0);
          bool targetPower = (rules[i].stateVal != 0);
          if (currentPowerState == targetPower && (millis() - rules[i].lastTriggeredTime > 1000)) {
            rules[i].lastTriggeredTime = millis();
            executeAction(rules[i]);
          }
        } else if (rules[i].stateType == 1) { // Preset change trigger
          if (currentPreset == rules[i].stateVal && rules[i].stateVal > 0 && (millis() - rules[i].lastTriggeredTime > 1000)) {
            rules[i].lastTriggeredTime = millis();
            executeAction(rules[i]);
          }
        }
      }
    }
  }

  bool onMqttMessage(char* topic, char* payload) override {
    if (!enabled || !initDone || !topic || !payload || isExecuting) return false;

    for (uint8_t i = 0; i < ruleCount; i++) {
      if (!rules[i].enabled || rules[i].triggerType != TRIG_MQTT) continue;

      if (strcmp(topic, rules[i].mqttTopic) == 0) {
        if (strlen(rules[i].mqttPayload) == 0 || strcmp(payload, rules[i].mqttPayload) == 0) {
          executeAction(rules[i]);
          return true;
        }
      }
    }
    return false;
  }

  // API State handler - allows reading and modifying automation rules via JSON API
  void addToJsonState(JsonObject& root) override {
    JsonObject top = root.createNestedObject(FPSTR(_name));
    top["enabled"] = enabled;
    top["count"] = ruleCount;

    JsonArray rulesArray = top.createNestedArray("rules");
    for (uint8_t i = 0; i < ruleCount; i++) {
      JsonObject r = rulesArray.createNestedObject();
      r["id"] = rules[i].id;
      r["enabled"] = rules[i].enabled;
      r["name"] = rules[i].name;
      r["trigType"] = (uint8_t)rules[i].triggerType;
      r["timeH"] = rules[i].timeHour;
      r["timeM"] = rules[i].timeMinute;
      r["days"] = rules[i].daysOfWeek;
      r["solarType"] = rules[i].solarType;
      r["solarOffset"] = rules[i].solarOffset;
      r["stateType"] = rules[i].stateType;
      r["stateVal"] = rules[i].stateVal;
      r["mqttTopic"] = rules[i].mqttTopic;
      r["mqttPayload"] = rules[i].mqttPayload;
      r["actType"] = (uint8_t)rules[i].actionType;
      r["presetId"] = rules[i].presetId;
      r["powerState"] = rules[i].powerState;
      r["apiCommand"] = rules[i].apiCommand;
    }
  }

  void readFromJsonState(JsonObject& root) override {
    JsonObject top = root[FPSTR(_name)];
    if (top.isNull()) return;

    if (top.containsKey("enabled")) {
      enabled = top["enabled"] | enabled;
    }

    if (top.containsKey("rules")) {
      JsonArray rulesArray = top["rules"].as<JsonArray>();
      ruleCount = 0;
      for (JsonObject r : rulesArray) {
        if (ruleCount >= AUTOMATION_ENGINE_MAX_RULES) break;

        AutomationRule& rule = rules[ruleCount];
        rule.id = r["id"] | (ruleCount + 1);
        rule.enabled = r["enabled"] | true;
        safeCopy(rule.name, r["name"] | "", sizeof(rule.name));
        rule.triggerType = (TriggerType)(r["trigType"] | 0);
        rule.timeHour = r["timeH"] | 0;
        rule.timeMinute = r["timeM"] | 0;
        rule.daysOfWeek = r["days"] | 0x7F;
        rule.solarType = r["solarType"] | 0;
        rule.solarOffset = r["solarOffset"] | 0;
        rule.stateType = r["stateType"] | 0;
        rule.stateVal = r["stateVal"] | 0;
        safeCopy(rule.mqttTopic, r["mqttTopic"] | "", sizeof(rule.mqttTopic));
        safeCopy(rule.mqttPayload, r["mqttPayload"] | "", sizeof(rule.mqttPayload));
        rule.actionType = (ActionType)(r["actType"] | 0);
        rule.presetId = r["presetId"] | 1;
        rule.powerState = r["powerState"] | 2;
        safeCopy(rule.apiCommand, r["apiCommand"] | "", sizeof(rule.apiCommand));

        ruleCount++;
      }
      saveRules();
    }
  }

  void addToConfig(JsonObject& root) override {
    JsonObject top = root.createNestedObject(FPSTR(_name));
    top["enabled"] = enabled;
  }

  bool readFromConfig(JsonObject& root) override {
    JsonObject top = root[FPSTR(_name)];
    if (top.isNull()) return false;
    enabled = top["enabled"] | enabled;
    return true;
  }

  // Load rules from flash storage (/automations.json)
  void loadRules() {
    if (!WLED_FS.exists(AUTOMATION_ENGINE_FILE_PATH)) {
      ruleCount = 0;
      return;
    }

    File f = WLED_FS.open(AUTOMATION_ENGINE_FILE_PATH, "r");
    if (!f) return;

    DynamicJsonDocument doc(2048);
    DeserializationError err = deserializeJson(doc, f);
    f.close();

    if (err) {
      DEBUG_PRINTLN("Automation Engine: Failed to parse /automations.json");
      return;
    }

    ruleCount = 0;
    JsonArray rulesArray = doc["rules"].as<JsonArray>();
    for (JsonObject r : rulesArray) {
      if (ruleCount >= AUTOMATION_ENGINE_MAX_RULES) break;

      AutomationRule& rule = rules[ruleCount];
      rule.id = r["id"] | (ruleCount + 1);
      rule.enabled = r["enabled"] | true;
      safeCopy(rule.name, r["name"] | "", sizeof(rule.name));
      rule.triggerType = (TriggerType)(r["trigType"] | 0);
      rule.timeHour = r["timeH"] | 0;
      rule.timeMinute = r["timeM"] | 0;
      rule.daysOfWeek = r["days"] | 0x7F;
      rule.solarType = r["solarType"] | 0;
      rule.solarOffset = r["solarOffset"] | 0;
      rule.stateType = r["stateType"] | 0;
      rule.stateVal = r["stateVal"] | 0;
      safeCopy(rule.mqttTopic, r["mqttTopic"] | "", sizeof(rule.mqttTopic));
      safeCopy(rule.mqttPayload, r["mqttPayload"] | "", sizeof(rule.mqttPayload));
      rule.actionType = (ActionType)(r["actType"] | 0);
      rule.presetId = r["presetId"] | 1;
      rule.powerState = r["powerState"] | 2;
      safeCopy(rule.apiCommand, r["apiCommand"] | "", sizeof(rule.apiCommand));

      ruleCount++;
    }
  }

  // Save rules to flash storage (/automations.json)
  void saveRules() {
    File f = WLED_FS.open(AUTOMATION_ENGINE_FILE_PATH, "w");
    if (!f) return;

    DynamicJsonDocument doc(2048);
    doc["enabled"] = enabled;
    JsonArray rulesArray = doc.createNestedArray("rules");

    for (uint8_t i = 0; i < ruleCount; i++) {
      JsonObject r = rulesArray.createNestedObject();
      r["id"] = rules[i].id;
      r["enabled"] = rules[i].enabled;
      r["name"] = rules[i].name;
      r["trigType"] = (uint8_t)rules[i].triggerType;
      r["timeH"] = rules[i].timeHour;
      r["timeM"] = rules[i].timeMinute;
      r["days"] = rules[i].daysOfWeek;
      r["solarType"] = rules[i].solarType;
      r["solarOffset"] = rules[i].solarOffset;
      r["stateType"] = rules[i].stateType;
      r["stateVal"] = rules[i].stateVal;
      r["mqttTopic"] = rules[i].mqttTopic;
      r["mqttPayload"] = rules[i].mqttPayload;
      r["actType"] = (uint8_t)rules[i].actionType;
      r["presetId"] = rules[i].presetId;
      r["powerState"] = rules[i].powerState;
      r["apiCommand"] = rules[i].apiCommand;
    }

    serializeJson(doc, f);
    f.close();
  }

  uint16_t getId() override {
    return USERMOD_ID_UNSPECIFIED;
  }
};
// AI: end
