#include "usermod_v2_automation_engine.h"

// AI: below section was generated by an AI
// Define static name string
const char UsermodAutomationEngine::_name[] PROGMEM = "AutomationEngine";

// Instantiation and registration of Automation Engine Usermod
#ifdef USERMOD_AUTOMATION_ENGINE
static UsermodAutomationEngine automationEngineUsermod;
REGISTER_USERMOD(automationEngineUsermod);
#endif
// AI: end
